backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Folder where uploaded files will be stored
public_folder: "/images/uploads" # Folder path used in the content

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
